/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.camaleon.view;

import com.camaleon.entities.Attribute;
import com.camaleon.entities.Table;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.JDBCType;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author ASUS
 */
public class Script extends javax.swing.JFrame {

    App padre = null;
    List<Table> tables = null;

    DefaultComboBoxModel<Attribute> dCBMAtributos = new DefaultComboBoxModel<>();
    DefaultComboBoxModel<String> dCBMTables = new DefaultComboBoxModel<>();

    /**
     * Creates new form Script
     */
    public Script(javax.swing.JFrame parent, List<Table> tables) {
        this.tables = tables;
        this.padre = (App) parent;
        initComponents();
        
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        
        selTable.setModel(dCBMTables);
        selTipo.setModel(new DefaultComboBoxModel(JDBCType.values()));
        selAtributo.setModel(dCBMAtributos);
        if (!tables.isEmpty()) {
            populateTables();
            populateAttributes(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        selTable = new javax.swing.JComboBox<>();
        lblTableSelect = new javax.swing.JLabel();
        lblStep1 = new javax.swing.JLabel();
        selAtributo = new javax.swing.JComboBox<>();
        lblAtributo = new javax.swing.JLabel();
        lblStep2 = new javax.swing.JLabel();
        lblStep3 = new javax.swing.JLabel();
        selTipo = new javax.swing.JComboBox<>();
        lblAtributo1 = new javax.swing.JLabel();
        btnGuardarTipo = new javax.swing.JButton();
        lblNombreTabla = new javax.swing.JLabel();
        txtTableName = new javax.swing.JTextField();
        btnGuardarNombreTabla = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnGenerarScript = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Generar script");

        selTable.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        selTable.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                selTableItemStateChanged(evt);
            }
        });

        lblTableSelect.setText("Tabla:");

        lblStep1.setText("1. Seleccione una tabla");

        selAtributo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                selAtributoItemStateChanged(evt);
            }
        });

        lblAtributo.setText("Atributo:");

        lblStep2.setText("2. Seleccione un atributo");

        lblStep3.setText("3. Seleccione el tipo de dato");

        lblAtributo1.setText("Tipo:");

        btnGuardarTipo.setText("Guardar Tipo");
        btnGuardarTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarTipoActionPerformed(evt);
            }
        });

        lblNombreTabla.setText("Nombre Tabla:");

        btnGuardarNombreTabla.setText("Guardar Nombre Tabla");
        btnGuardarNombreTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarNombreTablaActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnGenerarScript.setText("Generar script");
        btnGenerarScript.setEnabled(false);
        btnGenerarScript.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarScriptActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNombreTabla)
                                    .addComponent(lblTableSelect))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(selTable, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtTableName)))
                            .addComponent(lblStep2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblAtributo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                                .addComponent(selAtributo, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblStep3)
                                    .addComponent(lblStep1))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnGuardarNombreTabla))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblAtributo1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(selTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGuardarTipo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnGenerarScript)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancelar)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblStep1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTableSelect))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreTabla)
                    .addComponent(txtTableName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGuardarNombreTabla)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblStep2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAtributo)
                    .addComponent(selAtributo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblStep3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAtributo1)
                    .addComponent(selTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGuardarTipo)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnGenerarScript))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarTipoActionPerformed
        int tableSelected = selTable.getSelectedIndex();
        Table table = tables.get(tableSelected);
        List<Attribute> attributes = table.getAttributes();
        int attrSelected = selAtributo.getSelectedIndex();
        Attribute attribute = attributes.get(attrSelected);
        JDBCType type = (JDBCType) selTipo.getSelectedItem();
        
        tables.stream().forEach(t -> t.getAttributes().stream().filter(a -> a.getName().equals(attribute.getName())).forEach(a -> a.setType(type)));
        
        rePaintSelAttribute(dCBMAtributos);
        
        long noTypeAttributeTables = tables.stream().filter(t -> t.getAttributes().stream().filter(a -> a.getType()==null).count()>0).count();
        if(noTypeAttributeTables == 0){
            btnGenerarScript.setEnabled(true);
        }
        
    }//GEN-LAST:event_btnGuardarTipoActionPerformed

    private void selAtributoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_selAtributoItemStateChanged
        Table table = tables.get(selTable.getSelectedIndex());
        List<Attribute> attributes = table.getAttributes();
        int attrSelected = selAtributo.getSelectedIndex();
        if (attrSelected > -1) {
            Attribute attribute = attributes.get(attrSelected);
            if (attribute.getType() != null) {
                selTipo.setSelectedItem(attribute.getType());
            }
        }
    }//GEN-LAST:event_selAtributoItemStateChanged

    private void selTableItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_selTableItemStateChanged
        int selectedTableIndex = selTable.getSelectedIndex();
        if (selectedTableIndex > -1) {
            populateAttributes(selectedTableIndex);
            Table table = tables.get(selectedTableIndex);
            txtTableName.setText(table.getTableName());
        }
    }//GEN-LAST:event_selTableItemStateChanged

    private void btnGuardarNombreTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarNombreTablaActionPerformed
        int selectedTableIndex = selTable.getSelectedIndex();
        if (selectedTableIndex > -1) {
            Table table = tables.get(selectedTableIndex);
            table.setTableName(txtTableName.getText());
            populateTables();
            selTable.setSelectedIndex(selectedTableIndex);
        }
    }//GEN-LAST:event_btnGuardarNombreTablaActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGenerarScriptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarScriptActionPerformed
        StringBuilder sb =  new StringBuilder();
        StringBuilder sbAttributes;
        
        for(Table table : tables){
            sb.append("CREATE TABLE ");
            sb.append(table.getTableName());
            sb.append(" (");
            sbAttributes = new StringBuilder();
            for(Attribute attribute : table.getAttributes()){
                if(sbAttributes.length()>0){
                    sbAttributes.append(",");
                }
                sbAttributes.append("\n");
                sbAttributes.append("\t");
                sbAttributes.append(attribute.getName());
                sbAttributes.append(" ");
                sbAttributes.append(attribute.getType());
            }
            sb.append(sbAttributes);
            sb.append("\n);");
            sb.append("\n");
        }
        System.out.println(sb.toString());
    }//GEN-LAST:event_btnGenerarScriptActionPerformed

    private void populateAttributes(int tableIndex) {
        dCBMAtributos.removeAllElements();
        Table table = tables.get(tableIndex);

        table.getAttributes().forEach(attribute -> dCBMAtributos.addElement(attribute));
    }
    
    private void populateTables() {
        dCBMTables.removeAllElements();
        List<String> tableNames = this.tables.stream().map(t -> t.getTableName()).collect(Collectors.toList());
        tableNames.stream().forEach(t -> dCBMTables.addElement(t));
    }

    private void rePaintSelAttribute(DefaultComboBoxModel model) {
        int tableSelected = selTable.getSelectedIndex();
        if (tableSelected > -1) {
            int attrSelected = selAtributo.getSelectedIndex();
            model.removeAllElements();
            Table table = tables.get(tableSelected);
            for (Attribute attribute : table.getAttributes()) {
                model.addElement(attribute);
            }
            selAtributo.setSelectedIndex(attrSelected);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Script.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Script.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Script.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Script.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Script(null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGenerarScript;
    private javax.swing.JButton btnGuardarNombreTabla;
    private javax.swing.JButton btnGuardarTipo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAtributo;
    private javax.swing.JLabel lblAtributo1;
    private javax.swing.JLabel lblNombreTabla;
    private javax.swing.JLabel lblStep1;
    private javax.swing.JLabel lblStep2;
    private javax.swing.JLabel lblStep3;
    private javax.swing.JLabel lblTableSelect;
    private javax.swing.JComboBox<Attribute> selAtributo;
    private javax.swing.JComboBox<String> selTable;
    private javax.swing.JComboBox<JDBCType> selTipo;
    private javax.swing.JTextField txtTableName;
    // End of variables declaration//GEN-END:variables
}
