/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.camaleon.view;

import com.camaleon.entities.Attribute;
import com.camaleon.entities.Table;
import java.sql.JDBCType;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author ASUS
 */
public class Script extends javax.swing.JFrame {

    App padre = null;
    List<Table> tables = null;

    DefaultComboBoxModel<Attribute> dCBMAtributos = new DefaultComboBoxModel<>();

    /**
     * Creates new form Script
     */
    public Script(javax.swing.JFrame parent, List<Table> tables) {
        this.tables = tables;
        this.padre = (App) parent;
        initComponents();
        List<String> tableNames = this.tables.stream().map(t -> t.getTableName()).collect(Collectors.toList());
        selTable.setModel(new DefaultComboBoxModel(tableNames.toArray()));
        selTipo.setModel(new DefaultComboBoxModel(JDBCType.values()));
        selAtributo.setModel(dCBMAtributos);
        if (!tables.isEmpty()) {
            populateAttributes(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        selTable = new javax.swing.JComboBox<>();
        lblTableSelect = new javax.swing.JLabel();
        lblStep1 = new javax.swing.JLabel();
        selAtributo = new javax.swing.JComboBox<>();
        lblAtributo = new javax.swing.JLabel();
        lblStep2 = new javax.swing.JLabel();
        lblStep3 = new javax.swing.JLabel();
        selTipo = new javax.swing.JComboBox<>();
        lblAtributo1 = new javax.swing.JLabel();
        btnGuardarTipo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        selTable.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        selTable.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                selTableItemStateChanged(evt);
            }
        });

        lblTableSelect.setText("Tabla:");

        lblStep1.setText("1. Seleccione una tabla");

        selAtributo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                selAtributoItemStateChanged(evt);
            }
        });

        lblAtributo.setText("Atributo:");

        lblStep2.setText("2. Seleccione un atributo");

        lblStep3.setText("3. Seleccione el tipo de dato");

        lblAtributo1.setText("Tipo:");

        btnGuardarTipo.setText("Guardar Tipo");
        btnGuardarTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarTipoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblTableSelect)
                                .addGap(18, 18, 18)
                                .addComponent(selTable, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblAtributo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(selAtributo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblStep3)
                                    .addComponent(lblStep2)
                                    .addComponent(lblStep1))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(lblAtributo1)
                        .addGap(18, 18, 18)
                        .addComponent(selTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnGuardarTipo)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblStep1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTableSelect))
                .addGap(19, 19, 19)
                .addComponent(lblStep2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAtributo)
                    .addComponent(selAtributo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(lblStep3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAtributo1))
                .addGap(18, 18, 18)
                .addComponent(btnGuardarTipo)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selTableItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_selTableItemStateChanged
        populateAttributes(selTable.getSelectedIndex());
    }//GEN-LAST:event_selTableItemStateChanged

    private void selAtributoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_selAtributoItemStateChanged
        Table table = tables.get(selTable.getSelectedIndex());
        List<Attribute> attributes = table.getAttributes();
        int attrSelected = selAtributo.getSelectedIndex();
        if (attrSelected > -1) {
            Attribute attribute = attributes.get(attrSelected);
            if (attribute.getType() != null) {
                selTipo.setSelectedItem(attribute.getType());
            }
        }
    }//GEN-LAST:event_selAtributoItemStateChanged

    private void btnGuardarTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarTipoActionPerformed
        int tableSelected = selTable.getSelectedIndex();
        Table table = tables.get(tableSelected);
        List<Attribute> attributes = table.getAttributes();
        int attrSelected = selAtributo.getSelectedIndex();
        Attribute attribute = attributes.get(attrSelected);
        JDBCType type = (JDBCType) selTipo.getSelectedItem();
        attribute.setType(type);
        for(Table t : tables){
            List<Attribute> collect = t.getAttributes().stream().filter(a -> a.getName().equals(attribute.getName())).collect(Collectors.toList());
            if(collect.size()>0){
                collect.stream().forEach(a -> a.setType(type));
            }
        }
        rePaintSelAttribute(dCBMAtributos);
    }//GEN-LAST:event_btnGuardarTipoActionPerformed

    private void populateAttributes(int tableIndex) {

        dCBMAtributos.removeAllElements();
        Table table = tables.get(tableIndex);

        for (Attribute attribute : table.getAttributes()) {
            dCBMAtributos.addElement(attribute);
        }
    }
    
    private void rePaintSelAttribute(DefaultComboBoxModel model) {
        int tableSelected = selTable.getSelectedIndex();
        if(tableSelected>-1){
            int attrSelected = selAtributo.getSelectedIndex();
            model.removeAllElements();
            Table table = tables.get(tableSelected);
            for(Attribute attribute : table.getAttributes()){
                model.addElement(attribute);
            }
            selAtributo.setSelectedIndex(attrSelected);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Script.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Script.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Script.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Script.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Script(null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarTipo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAtributo;
    private javax.swing.JLabel lblAtributo1;
    private javax.swing.JLabel lblStep1;
    private javax.swing.JLabel lblStep2;
    private javax.swing.JLabel lblStep3;
    private javax.swing.JLabel lblTableSelect;
    private javax.swing.JComboBox<Attribute> selAtributo;
    private javax.swing.JComboBox<String> selTable;
    private javax.swing.JComboBox<JDBCType> selTipo;
    // End of variables declaration//GEN-END:variables
}
